apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-v2-deployment
  labels:
    app: api-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-v2
  template:
    metadata:
      labels:
        app: api-v2
    spec:
      containers:
      - name: api-v2
        image: hashicorp/http-echo
        args:
          - "-text=API V2 🚀"
          - "-listen=:8080"
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-v2-service
spec:
  selector:
    app: api-v2
  ports:
    - port: 8080
      targetPort: 8080
