apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-v1-deployment
  labels:
    app: api-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-v1
  template:
    metadata:
      labels:
        app: api-v1
    spec:
      containers:
      - name: api-v1
        image: hashicorp/http-echo
        args:
          - "-text=API V1 🚀"
          - "-listen=:8080"
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-v1-service
spec:
  selector:
    app: api-v1
  ports:
    - port: 8080
      targetPort: 8080
